const images = {
    man_phone: require('./src/man_phone.jpg'),
    // man_phone_svg: require('./src/man_phone.svg'),
    // girl_taking_funny_photo : require('./src/girl_taking_funny_photo.png')
    // undraw_Mobile_user_re_xta4 : require('./src/undraw_Mobile_user_re_xta4.png'),
    sign_up: require('./src/sign_up.png'),
    log_in: require('./src/log_in.png'),
    OTP_verification: require('./src/OTP_verification.png'),
    two_step_verify: require('./src/two_step_verify.jpg'),
    refer: require('./src/refer.jpg'),
    wallet: require('./src/wallet.png'),
    withdraw: require('./src/wallet.png'),
    banner: require('./src/banner.jpg'),
    offers: require('./src/offers.webp'),
    // smartphone: require('./src/smartphone.jpg'),
    girl: require('./src/girl.jpg'),
    girl_2 : require('./src/girl_2.jpg'),
    gaming : require('./src/gaming.jpg'),
    spinWheel : require('./src/spinWheel.jpg'),
    coins : require('./src/coins.jpg'),
    bell : require('./src/bell.jpg'),
    // offer : require('./src/offer.jpg'),
    // coins_mobile : require('./src/coins_mobile.jpg'),
    // update_available : require('./src/update_available.jpg'),
    update_available_2 : require('./src/update_available_2.png'),
    congrats : require('./src/congrats.jpg'),
}
export default images